/*Description: A C program for a match-stick game between the computer and a user.This
program ensures that the computer always wins. Rules for the game are as
follows:
1. There are 21 matchsticks.
2. The computer asks the player to pick 1,2,3 or 4 match sticks.
3. After the person picks, the computer does its picking.
4. Whoever is forced to pick up the last matchstick loses the game.*/
/*
*Programmer:Adina
*Date:03October2023
*/
#include <stdio.h>
#include <stdlib.h>
#include<time.h>

int main()
{
	int n, number, input;
	n=21;
	while(n>4)
	{
		printf("\nEnter any number between 1 and 4: ");
		scanf("%d",&input);
		n=n-input;
		srand(time(NULL));//Here a new function is used to generate a random integer
						  //between the range of 1 and 4
		number=(rand()%(4-1+1))+1;
		printf("\nNumber generated by computer: %d",number);
		n=n-number;
	}
	n=n-(n-1);
	printf("\nEnter any number between 1 and 4: ");
	scanf("%d",&input);
	printf("\nYou lost!");
}
